# Site settings
title: RNDuja Blog
header-img: img/home-bg.jpg
email: fabiofumarola@gmail.com
description: "a group of people that like spicy nduja"
baseurl: ""
url: ""
twitter_username: rnduja
github_username:  rnduja
facebook_username: rnduja

# Build settings
#markdown: kramdown
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
