# Site settings
title: RNDuja Blog
header-img: img/home-bg.png
email: rnduja@gmail.com
description: "a group of people that like spicy nduja"
baseurl: ""
url: ""
twitter_username: rnduja
github_username:  rnduja
facebook_username: rnduja

# Build settings
#markdown: kramdown
permalink: pretty
markdown: kramdown
# kramdown:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
